[package]
name = "flite-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
cstr = "0.2.11"

[build-dependencies]
walkdir = "2.3.3"
bindgen = "0.65.1"
cc = "1"

[dev-dependencies]
hound = "3.5"
rodio = { version = "0.17.1", default_features = false, features = [ "wav" ] }
